"""
LangGraph state model for workflow orchestration.

Defines the shared state that flows through the agent workflow.
"""

from typing import Annotated, List, Optional

from pydantic import BaseModel, Field, ConfigDict

from src.models.damage import DamageClaim
from src.models.events import BaseEvent
from src.models.financial import CostEstimate, Invoice, RetirementAnalysis
from src.models.routing import ValidationResult, CustomerRiskProfile


class WorkflowError(BaseModel):
    """Error that occurred during workflow execution."""
    timestamp: str
    stage: str
    error_type: str
    message: str
    recoverable: bool = Field(default=True)
    retry_count: int = Field(default=0)


class Notification(BaseModel):
    """Notification to be sent to stakeholders."""
    notification_id: str
    recipient: str
    notification_type: str  # customer, finance, operations, fleet_management
    subject: str
    body: str
    channel: str = Field(default="email")
    sent: bool = Field(default=False)


class DamageClaimState(BaseModel):
    """
    Complete state for damage claim workflow.

    This is the TypedDict equivalent using Pydantic for type safety.
    Flows through all LangGraph nodes.
    """

    # === Core Claim Data ===
    claim: DamageClaim = Field(..., description="The damage claim being processed")

    # === Enriched Context ===
    # (Added by Context Enrichment Agent)
    customer_risk_profile: Optional[CustomerRiskProfile] = None

    # === Processing Results ===
    # (Added by respective agents)
    cost_estimate: Optional[CostEstimate] = None
    validation_result: Optional[ValidationResult] = None
    invoice: Optional[Invoice] = None
    retirement_analysis: Optional[RetirementAnalysis] = None

    # === AI Reasoning ===
    # (AI-powered agent reasoning for transparency and audit)
    ai_cost_reasoning: Optional[str] = Field(
        default=None,
        description="LLM reasoning for cost estimation (edge cases only)"
    )
    ai_validation_reasoning: Optional[str] = Field(
        default=None,
        description="LLM reasoning for validation decision (ambiguous patterns)"
    )

    # === Events ===
    # (Published at each stage for event-driven architecture)
    events: List[BaseEvent] = Field(default_factory=list)

    # === Notifications ===
    # (Generated by Notification Agent)
    notifications: List[Notification] = Field(default_factory=list)

    # === Errors & Recovery ===
    errors: List[WorkflowError] = Field(default_factory=list)
    requires_retry: bool = Field(default=False)
    retry_count: int = Field(default=0)

    # === Routing & Decision ===
    next_step: Optional[str] = Field(
        default=None,
        description="Next step in workflow (for conditional routing)"
    )
    workflow_complete: bool = Field(default=False)
    requires_human_approval: bool = Field(default=False)
    approval_granted: Optional[bool] = None

    # === Metadata ===
    workflow_started_at: Optional[str] = None
    workflow_completed_at: Optional[str] = None
    processing_time_seconds: Optional[float] = None

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "claim": {
                    "claim_id": "CLM-2026-001",
                    "vehicle_id": "VW-POLO-2023-001",
                    "customer_id": "CUST-5678"
                },
                "workflow_complete": False,
                "requires_human_approval": False
            }
        }


    )


# Type annotations for LangGraph
# These help with type checking and IDE support
StateAnnotation = Annotated[DamageClaimState, "Workflow state for damage claim processing"]
